---
- name: Instalar un repositorio y dependencias
  hosts: mi_servidor  # Aquí puedes poner el nombre de un grupo de hosts o la IP de un servidor remoto
  become: true  # Necesario si se requiere permisos de superusuario (sudo)
  tasks:
    - name: Instalar repositorio EPEL (Extra Packages for Enterprise Linux)
      ansible.builtin.apt:
        name: epel-release
        state: present

    - name: Instalar git y curl
      ansible.builtin.apt:
        name:
          - git
          - curl
        state: present
