---
- name: Enviar correo de prueba desde Mailtrap
  hosts: all
  become: yes

  tasks:
    - name: Enviar correo de prueba
      community.general.mail:
        host: sandbox.smtp.mailtrap.io
        port: 587
        username: "aae51fed434def"  # Usa tu nombre de usuario Mailtrap
        password: "178ca954325ca6"  # Usa tu contraseña Mailtrap
        to: "angeljesus@gmail.com"  # Dirección del destinatario
        subject: "Correo de prueba desde Ansible con Mailtrap"
        body: "Este es un correo de prueba enviado desde Ansible utilizando Mailtrap.io."
        secure: starttls  # Conexión segura usando STARTTLS


