- hosts: localhost
  gather_facts: no  # No es necesario recopilar hechos si solo queremos un mensaje simple

  tasks:
    - name: Imprimir un mensaje de "Hola Mundo"
      debug:
        msg: "¡Hola Mundo desde Ansible!"
