---
- name: Install collection and generate SSH key
  hosts: all
  become: yes

  tasks:
    - name: Install community.crypto collection
      ansible.builtin.ansible_galaxy:
        name: community.crypto
        source: https://galaxy.ansible.com

    - name: Generate SSH keypair
      community.crypto.openssh_keypair:
        path: /home/ansible/.ssh/id_ssh_rsa
        type: rsa
        size: 4096
        state: present

