---
- name: Instalar y asegurar que nginx esté corriendo
  hosts: mi_servidor
  become: true
  tasks:
    - name: Verificar si nginx está instalado
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Asegurarse de que nginx esté corriendo
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
