- name: Instalar el paquete htop
  hosts: mi_servidor
  become: true
  tasks:
    - name: Verificar conectividad con el servidor
      ansible.builtin.ping:
    
    - name: Instalar htop
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: yes
