---
- name: Asegurarse de que el repositorio de MySQL esté presente
  apt_repository:
    repo: 'deb http://repo.mysql.com/apt/ubuntu/ focal mysql-8.0'
    state: present
    filename: mysql

- name: Actualizar los paquetes APT
  apt:
    update_cache: yes

- name: Instalar MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Asegurar que MySQL esté en ejecución
  service:
    name: mysql
    state: started
    enabled: yes

- name: Configurar la contraseña de root de MySQL
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present

- name: Asegurarse de que MySQL esté en ejecución y habilitado
  service:
    name: mysql
    state: started
    enabled: yes
